### ISSUE TITLE
URL 下划线未对齐

### ISSUE THREAD

**Issue by KevinSJ** [huhubun/BunLab#1]
在 Chrome 下 当放大等级为100%时，UA viewer链接的下划线未对齐

**Comment by huhubun** [comment]
我认为这是浏览器在不同分辨率或 DPI 下对 `text-decoration: underline dashed;` 渲染有问题造成的

**Comment by huhubun** [comment]
我不打算针对 Chrome 修正这个问题，为此我需要修改下划线的实现方式，例如改为通过 `border-bottom` 实现。下划线在 Firefox 上它是正常的，我打算关闭这个 issue。

**Comment by KevinSJ** [comment]
鉴于 Chrome 在浏览器市场所占的份额，我依然建议修复此问题。此问题可通过添加text-decoration-skip-ink:none css属性解决，这是一个已知的chrome bug
参见：[1]( https://stackoverflow.com/a/50008655/6174487), [2](https://bugs.chromium.org/p/chromium/issues/detail?id=808603)

**Comment by huhubun** [comment]
我只是不愿意对特定浏览器做 hack，在我有时间的时候我会再思考这个问题再决定是否修复。感谢您与我探讨这一话题 ☺

**Comment by huhubun** [comment]
因为更改了设计方案，不再存在该问题，所以关闭本 issue。
